version: "3"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
    networks:
      - omero
    volumes:
      - "database:/var/lib/postgresql/data"
    ports:
        - "5432:5432"

  omeroserver:
    image: "openmicroscopy/omero-server:5.6"
    environment:
      CONFIG_omero_db_host: database
      CONFIG_omero_db_user: omero
      CONFIG_omero_db_pass: omero
      CONFIG_omero_db_name: omero
      CONFIG_omero_ldap_config: "true"
      CONFIG_omero_ldap_urls: "ldap://ldap:10389"
      CONFIG_omero_ldap_base: "dc=openmicroscopy,dc=org"
      CONFIG_omero_ldap_group__filter: "(objectClass=groupOfUniqueNames)"
      CONFIG_omero_ldap_group__mapping: "name=cn"
      CONFIG_omero_ldap_new__user__group: "MyData"
      CONFIG_omero_ldap_new__user__group_owner: "(owner=@{dn})"
      CONFIG_omero_ldap_password: "secret"
      CONFIG_omero_ldap_sync__on__login: "true"
      CONFIG_omero_ldap_user__filter: "(objectClass=person)"
      CONFIG_omero_ldap_user__mapping: "omeName=uid,firstName=givenName,lastName=sn,email"
      CONFIG_omero_ldap_username: "uid=admin,ou=system"
      ROOTPASS: omero
    networks:
      - omero
    ports:
      - "4063:4063"
      - "4064:4064"
    volumes:
      - "omero:/OMERO"

  omeroweb:
    image: "openmicroscopy/omero-web-standalone:5.6"
    environment:
      OMEROHOST: omeroserver
    networks:
      - omero
    ports:
      - "4080:4080"

  ldap:
    image: "openmicroscopy/apacheds"
    networks:
      - omero
    ports:
        - "10389:10389"

networks:
  omero:

volumes:
  database:
  omero:
